// Generated by https://quicktype.io

export interface ICategory {
    id:         string;
    name:       string;
    image:      string;
    status:     number;
    created_at: string;
    updated_at: string;
    deleted_at: null;
}
