// Generated by https://quicktype.io

export interface IDashboard {
	totalSales: number;
	totalOrders: number;
	averageReviews: number;
	ordersByMonth: OrdersByMonth;
}

export interface OrdersByMonth {
	[key: string]: number;
}
