// Generated by https://quicktype.io

export interface IUser {
    id:         string;
    email:      string;
    first_name: string;
    last_name:  string;
    password:   string;
    user_name?: string; 
    role:       string;
    created_at: string;
    updated_at: string;
    deleted_at: null;
}
